name: Audit PR

on: [pull_request]

jobs:  
  prepare:
    outputs:
      formula: ${{ steps.set-output-matrix.outputs.formula }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: Formula/*.rb
          json: true
          
      - id: set-output-matrix
        run: |
          echo "formula=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
  audit:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formula: ${{ fromJSON(needs.prepare.outputs.formula) }}
    steps:
      - uses: actions/checkout@v3

      - uses: Homebrew/actions/setup-homebrew@master

      - name: audit bottle (${{ matrix.formula }})
        run: |
          brew audit --online ${{ matrix.formula }}
