name: Audit PR

on: [pull_request]

jobs:
  prepare:
    outputs:
      formula: ${{ steps.set-output-matrix.outputs.formula }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: Formula/*.rb
          json: true

      - id: set-output-matrix
        run: |
          echo "formula=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
  audit:
    needs: prepare
    strategy:
      matrix:
        formula: ${{ fromJSON(needs.prepare.outputs.formula) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Audit formula (${{ matrix.formula }})
        run: |
          brew audit --except license --os all --arch all --strict --online --git \
            ${{ github.repository }}/$(basename ${{ matrix.formula }} .rb)

      - name: Audit formula license (${{ matrix.formula }})
        run: |
          brew audit --only license --os all --arch all --strict --online --git \
            ${{ github.repository }}/$(basename ${{ matrix.formula }} .rb)

  install:
    needs: prepare
    if: '!cancelled()'
    strategy:
      matrix:
        formula: ${{ fromJSON(needs.prepare.outputs.formula) }}
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ strategy.matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install formula (${{ matrix.formula }})
        run: brew install --build-from-source ${{ github.repository }}/$(basename ${{ matrix.formula }} .rb )
